query movieDetails($tmdbId: ID!) {
  movie(tmdbId: $tmdbId) {
    movieId
    title
    summary
    cover
    releaseDate
    tmdbId
    userResponse {
      like
    }
    totalLikes
    totalDislikes
  }
}
