query paginatedMovies($userId: ID, $responseUserId: ID, $first: Int, $after: String) {
  user(id: $userId) {
    movies(first: $first, after: $after) {
      pageInfo {
        hasNextPage
        endCursor
        startCursor
      }
      edges {
        node {
          title
          totalLikes
          summary
          id
          tmdbId
          cover
          userResponse(userId: $responseUserId) {
            like
          }
        }
      }
    }
  }
}
