query recentMovies($first: Int, $after: String){
  recentMovies(first:$first, after: $after) {
    pageInfo{
      hasNextPage
      endCursor
      startCursor
    }
    edges {
      node {
        tmdbId
        title
        cover
        followeeLikes
        followeeDislikes
      }
    }
  }
}
