query notifications($first: Int, $after: String){
  user {
    notifications(first: $first, after: $after) {
      pageInfo {
        hasNextPage
        startCursor
        endCursor
      }
      edges {
        node {
          read
          createdAt
          __typename
          ... on MovieRecomendationNotificationType {
            fromUser {
              userId
              name
            }
            movie {
              movieId
              tmdbId
              cover
              title
            }
          }
          ... on NewFollowerNotificationType {
            follower {
              userId
              name
              photoUri
            }
          }
        }
      }
    }
  }
}
