query userDetails($userId: ID, $responseUserId: ID, $first: Int, $after: String) {
  user(id: $userId) {
    userId
    name
    email
    following
    followeeCount
    followerCount
    movies(first: $first, after: $after) {
      cover
      userResponse(userId: $responseUserId){
        like
      }
    }
  }
}
